name: nancylevan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49058
title: The Art of Nancy Levan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e6ac87'
    - '#acacac'
    - '#5d5d5d'
    - '#cd8e74'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
